apiVersion: v1
kind: Service
metadata:
  labels:
    app: coldfusion-kubernetes
    app.kubernetes.io/component: coldfusion-kubernetes
    app.kubernetes.io/instance: coldfusion-kubernetes
    app.kubernetes.io/name: coldfusion-kubernetes
    app.kubernetes.io/part-of: coldfusion-kubernetes-app
  name: coldfusion-kubernetes
  namespace: cfdemo
spec:
  ports:
  - port: 8080
    targetPort: 8500
  selector:
    app: coldfusion-kubernetes