apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coldfusion-kubernetes
    app.kubernetes.io/component: coldfusion-kubernetes
    app.kubernetes.io/instance: coldfusion-kubernetes
    app.kubernetes.io/name: coldfusion-kubernetes
    app.kubernetes.io/part-of: coldfusion-kubernetes-app
  name: coldfusion-kubernetes
  namespace: cfdemo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: coldfusion-kubernetes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: coldfusion-kubernetes
        deployment: coldfusion-kubernetes
    spec:
      serviceAccountName: coldfusion-runner-sa
      securityContext:
        runAsUser: 0
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/cfdemo/coldfusion-kubernetes:latest
        imagePullPolicy: Always
        name: coldfusion-kubernetes
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30